colors:
  dark:
    background: "#2E3440"
    text: "#5E81AC"
    accent: "#8FBCBB"
  light:
    background: "#ECEFF4"
    text: "#5E81AC"
    accent: "#88C0D0"
  icon: "#5E81AC"
apps:
  homeautomation:
    - icon: homeassistant
      name: homeassistant
      url: https://www.home-assistant.io/
    - icon: esphome
      name: esphome
      url: https://esphome.io/
    - icon: zigbee2mqtt
      name: zigbee2mqtt
      url: https://www.zigbee2mqtt.io/
    - icon: 374171/vscode
      name: codeserver
      url: https://code.visualstudio.com/
  monitoring:
    - icon: 353829/grafana
      name: grafana
      url: https://grafana.com/
  infrastructure:
    - icon: pihole
      name: pihole
      url: https://pi-hole.net/
    - icon: portainer
      name: portainer
      url: https://www.portainer.io/
    - icon: traefikproxy
      name: traefik
      url: https://traefik.io/traefik/
  media:
    - icon: 518568/photoprism
      name: photoprism
      url: https://www.photoprism.app/
    - icon: 475700/youtube-color
      name: youtube
      url: https://www.youtube.com/
  dev:
    - icon: https://upload.wikimedia.org/wikipedia/commons/b/bb/Gitea_Logo.svg
      name: gitea
      url: https://about.gitea.com/
bookmarks:
  homeautomation:
    - name: homeassistant
      url: https://www.home-assistant.io/
    - name: esphome
      url: https://esphome.io/
    - name: zigbee2mqtt
      url: https://www.zigbee2mqtt.io/
    - name: codeserver
      url: https://code.visualstudio.com/
  monitoring:
    - name: grafana
      url: https://grafana.com/
  infrastructure:
    - name: pihole
      url: https://pi-hole.net/
    - name: portainer
      url: https://www.portainer.io/
    - name: traefik
      url: https://traefik.io/traefik/
  media:
    - name: photoprism
      url: https://www.photoprism.app/
    - name: youtube
      url: https://www.youtube.com/
  dev:
    - name: gitea
      url: https://about.gitea.com/
